---
dates:
  semester_1:
    Freshers week:
      - start_date: "12/09/2022"
      - end_date: "18/09/2022"
    Teaching block 1:
      - start_date: "19/09/2022"
      - end_date: "04/12/2022"
    Assessment period:
      - start_date: "05/12/2022"
      - end_date: "16/12/2022"
    Winter holiday:
      - start_date: "19/12/2022"
      - end_date: "06/01/2023"
  semester_2:
    Consolidation:
      - start_date: "09/01/2023"
      - end_date: "15/01/2023"
    Teaching block 2:
      - start_date: "16/01/2023"
      - end_date: "02/04/2023"
    Spring holiday:
      - start_date: "03/04/2023"
      - end_date: "14/04/2023"
    Assessment period:
      - start_date: "17/04/2023"
      - end_date: "19/05/2023"
